api gateway school connection
CAMPUS-KID/kampus-kid-platform pull request #18
Opened 2022-10-16 01:19 UTC by nmejiab

## Background

Create the queries and mutations referent to the ms-school dependencies bye editing the schema, mutations and queries files, also add the documentation in the files "graphiQL-test.txt" and "query-variables.txt"

## Changes done

queries and mutations to the tables site, faculty and career.

## Pending to be done

Nothing

## Notes

No

## Demo

Result of making a get to all the tables after create some fields in each one by the GraphQl methods:
![image](https://user-images.githubusercontent.com/49196798/196013379-e8c0556c-71e1-4658-99ef-a90733696fe2.png)

2022-10-16 23:03 UTC, jhonatan247 requested changes
Good job, just some small comments.

2022-10-16 23:03 UTC, jhonatan247 commented on ag-campus-kid/src/microservices/school/mutations.js
> +    return await HttpProvider.deleted(`${baseUrl}/api/sites/` + id);
```suggestion
    return await HttpProvider.deleted(`${baseUrl}/api/sites/${id}`);
```

2022-10-16 23:03 UTC, jhonatan247 commented on ag-campus-kid/src/microservices/school/mutations.js
> +    return await HttpProvider.deleted(`${baseUrl}/api/faculties/` + id);
```suggestion
    return await HttpProvider.deleted(`${baseUrl}/api/faculties/${id}`);
```

2022-10-16 23:03 UTC, jhonatan247 commented on ag-campus-kid/src/microservices/school/mutations.js
> +    return await HttpProvider.deleted(`${baseUrl}/api/careers/` + id);
```suggestion
    return await HttpProvider.deleted(`${baseUrl}/api/careers/${id}`);
```

2022-10-17 04:39 UTC, nmejiab commented
Fix done

2022-10-17 14:12 UTC, jhonatan247 approved these changes

2022-10-17 14:12 UTC, merged